"""
================================================================================
  PROBABILITY FOR MACHINE LEARNING & DEEP LEARNING
  Complete Implementation — NumPy · Math · Torch · Sklearn · TensorFlow
================================================================================
  Covers all 20 sections from the reference document:
  Foundations → Axioms → Conditional Probability → Bayes' Theorem →
  Independence → Random Variables → Distributions (Discrete & Continuous) →
  Joint/Marginal/Conditional → Expectation → Variance & Covariance →
  MGF & Characteristic Functions → Information Theory → Inequalities →
  Limit Theorems → Bayesian Inference → Graphical Models →
  Exponential Family → MLE & MAP → Probabilistic ML/DL Models
================================================================================
"""

import math
import itertools
import warnings
import numpy as np
import torch
import torch.nn as nn
import tensorflow as tf
from scipy import stats
from scipy.special import gammaln, comb
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression, Ridge, Lasso
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.feature_selection import mutual_info_classif

warnings.filterwarnings("ignore")
np.random.seed(42)
torch.manual_seed(42)
tf.random.set_seed(42)

DIVIDER = "=" * 72
def header(title):  print(f"\n{DIVIDER}\n  {title}\n{DIVIDER}")
def sub(title):     print(f"\n  --- {title} ---")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 1 · Foundations of Probability
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 1 · Foundations of Probability")

sub("1.1 Sample Space & Events via Monte-Carlo")
# Die roll: Ω = {1,2,3,4,5,6}
N = 100_000
omega = np.random.randint(1, 7, N)   # simulate sample space

A = omega <= 3          # event A: {1,2,3}
B = omega >= 4          # event B: {4,5,6}
AB_union  = A | B       # A ∪ B
AB_inter  = A & B       # A ∩ B  (should be ∅)
A_comp    = ~A          # Aᶜ

print(f"  P(A)  = {A.mean():.4f}   expected 0.5")
print(f"  P(B)  = {B.mean():.4f}   expected 0.5")
print(f"  P(A∪B)= {AB_union.mean():.4f}  expected 1.0  (A,B partition Ω)")
print(f"  P(A∩B)= {AB_inter.mean():.4f}  expected 0.0  (mutually exclusive)")
print(f"  P(Aᶜ) = {A_comp.mean():.4f}  = 1 - P(A) ✓")

sub("1.2 De Morgan's Laws (numerical verification)")
# (A∪B)ᶜ = Aᶜ ∩ Bᶜ
C = omega == 6
lhs = ~(A | C)          # (A∪C)ᶜ
rhs = (~A) & (~C)       # Aᶜ ∩ Cᶜ
print(f"  De Morgan (A∪C)ᶜ = Aᶜ∩Cᶜ: {np.all(lhs == rhs)} ✓")

sub("1.3 Sigma-Algebra (closed under complement & union)")
# Smallest sigma-algebra generated by event A = {1,2,3} on die
Omega = frozenset({1, 2, 3, 4, 5, 6})
A_set = frozenset({1, 2, 3})
sigma_alg = {frozenset(), Omega, A_set, Omega - A_set}  # generated σ-algebra
print(f"  σ(A) = {len(sigma_alg)} elements: {{∅, Ω, A, Aᶜ}}")
for s in sigma_alg:
    complement = Omega - s
    assert complement in sigma_alg, "Not closed under complement!"
print("  Closed under complement ✓")

sub("1.4 Interpretations of Probability")
# Frequentist: lim n_A/n
flips = np.random.choice(['H','T'], size=10000)
freq_prob = np.mean(flips == 'H')
print(f"  Frequentist P(H) = {freq_prob:.4f}  (true = 0.5)")
# Classical: |A|/|Ω|
classical = len({1, 2, 3}) / len({1, 2, 3, 4, 5, 6})
print(f"  Classical  P(≤3) = {classical:.4f}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 2 · Axioms & Basic Rules
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 2 · Axioms & Basic Rules")

sub("2.1 Kolmogorov Axioms")
# P(Ω)=1,  P(A)≥0,  P(A∪B)=P(A)+P(B) for disjoint A,B
N = 100_000
rolls = np.random.randint(1, 7, N)
p_omega = np.ones(N).mean()                      # certainty
p_A = (rolls <= 2).mean()                        # A={1,2}
p_B = (rolls >= 5).mean()                        # B={5,6} – disjoint from A
p_AuB = ((rolls <= 2) | (rolls >= 5)).mean()
print(f"  Axiom 1: P(Ω)={p_omega:.1f}")
print(f"  Axiom 2: P(A)={p_A:.4f} ≥ 0 ✓")
print(f"  Axiom 3: P(A∪B)={p_AuB:.4f}  P(A)+P(B)={p_A+p_B:.4f} ✓")

sub("2.2 Derived Rules")
# Inclusion-Exclusion 2: P(A∪B)=P(A)+P(B)-P(A∩B)
E = (rolls <= 4).mean()    # {1,2,3,4}
F = (rolls >= 3).mean()    # {3,4,5,6}
EF_inter = ((rolls<=4)&(rolls>=3)).mean()
EuF_mc   = ((rolls<=4)|(rolls>=3)).mean()
EuF_ie   = E + F - EF_inter
print(f"  Inclusion-Exclusion: MC={EuF_mc:.4f}  IE={EuF_ie:.4f} ✓")

# Boole's inequality (Union Bound): P(A∪B) ≤ P(A)+P(B)
print(f"  Boole (union bound): P(E∪F)={EuF_mc:.4f} ≤ P(E)+P(F)={E+F:.4f} ✓")

# Inclusion-Exclusion 3 events
G = (rolls % 2 == 0).mean()   # P(even)
H_ = (rolls >= 3).mean()      # P(≥3)
I_ = (rolls <= 5).mean()      # P(≤5)
GH  = ((rolls%2==0)&(rolls>=3)).mean()
GI  = ((rolls%2==0)&(rolls<=5)).mean()
HI  = ((rolls>=3)&(rolls<=5)).mean()
GHI = ((rolls%2==0)&(rolls>=3)&(rolls<=5)).mean()
ie3 = G + H_ + I_ - GH - GI - HI + GHI
mc3 = ((rolls%2==0)|(rolls>=3)|(rolls<=5)).mean()
print(f"  Inclusion-Excl 3:  MC={mc3:.4f}  Formula={ie3:.4f} ✓")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 3 · Conditional Probability
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 3 · Conditional Probability")

sub("3.1 Definition: P(A|B) = P(A∩B)/P(B)")
rolls = np.random.randint(1, 7, 100_000)
A_cond = rolls <= 3
B_cond = rolls % 2 == 0   # even

p_A_and_B = (A_cond & B_cond).mean()
p_B_val   = B_cond.mean()
p_A_given_B_mc = (A_cond[B_cond]).mean()          # empirical conditional
p_A_given_B_formula = p_A_and_B / p_B_val         # definition
print(f"  P(A∩B)={p_A_and_B:.4f}  P(B)={p_B_val:.4f}")
print(f"  P(A|B) MC={p_A_given_B_mc:.4f}  Formula={p_A_given_B_formula:.4f} ✓")

sub("3.2 Chain Rule / Multiplication Rule")
# P(A∩B) = P(A|B)·P(B)
p_chain = p_A_given_B_formula * p_B_val
print(f"  P(A∩B) via chain rule = {p_chain:.4f}  direct = {p_A_and_B:.4f} ✓")

# Language model: P(w1,w2,...,wT) = Π P(wt|w1,...,wt-1)
# Simulate bigram probability
vocab = ['the', 'cat', 'sat', 'on', 'mat']
bigram_probs = {('the','cat'):0.4, ('cat','sat'):0.6,
                ('sat','on'):0.8,  ('on','mat'):0.7}
sentence = [('the','cat'), ('cat','sat'), ('sat','on'), ('on','mat')]
log_prob  = sum(math.log(bigram_probs[pair]) for pair in sentence)
print(f"  Language model log P(sentence) = {log_prob:.4f}")

sub("3.3 Law of Total Probability")
# P(A) = Σ P(A|Bᵢ)·P(Bᵢ)  — spam example from notes
p_spam      = 0.30
p_free_spam = 0.80
p_free_ham  = 0.10
p_free_total = p_free_spam * p_spam + p_free_ham * (1 - p_spam)
print(f"  P('free') = {p_free_total:.4f}  (0.31 expected)")

# Mixture model: p(x) = Σ π_k · p(x|z=k)
pi = np.array([0.3, 0.5, 0.2])
mu_mix = np.array([0.0, 5.0, -3.0])
x_obs  = 4.5
marginal_x = sum(pi[k] * stats.norm.pdf(x_obs, mu_mix[k], 1.0)
                 for k in range(3))
print(f"  Mixture p(x=4.5) = {marginal_x:.6f}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 4 · Bayes' Theorem
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 4 · Bayes' Theorem")

sub("4.1 Discrete Bayes: P(B|A)=P(A|B)·P(B)/P(A)")
def bayes(likelihood, prior, evidence):
    return likelihood * prior / evidence

# Medical test
p_disease = 0.01
sensitivity = 0.99        # P(+|D)
false_pos   = 0.05        # P(+|¬D)
p_pos = sensitivity * p_disease + false_pos * (1 - p_disease)
p_disease_given_pos = bayes(sensitivity, p_disease, p_pos)
print(f"  P(Disease|+) = {p_disease_given_pos:.4f}  ← base rate dominates despite 99% test")

sub("4.2 Continuous Bayes / Bayesian Linear Regression")
# Posterior ∝ Likelihood × Prior
# p(w|y,X) ∝ p(y|X,w)·p(w)  — closed form for Gaussian-Gaussian
np.random.seed(0)
n = 50
X_bl = np.random.randn(n, 1)
w_true = np.array([2.5])
y_bl = X_bl @ w_true + np.random.randn(n) * 0.5

sigma2_noise = 0.25     # known noise variance
sigma2_prior = 1.0      # prior: w ~ N(0, σ²_prior)

# Posterior: N(μ_post, σ²_post)
A_mat = X_bl.T @ X_bl / sigma2_noise + 1.0 / sigma2_prior
mu_post  = (X_bl.T @ y_bl / sigma2_noise) / A_mat
var_post = 1.0 / A_mat
print(f"  True w={w_true[0]}  Posterior mean={mu_post[0,0]:.4f}  ±{np.sqrt(var_post[0,0]):.4f}")

sub("4.3 Naive Bayes Classifier (sklearn)")
from sklearn.datasets import load_iris
iris = load_iris()
X_iris, y_iris = iris.data, iris.target
nb = GaussianNB()
nb.fit(X_iris, y_iris)
preds = nb.predict(X_iris)
acc = np.mean(preds == y_iris)
print(f"  Naive Bayes on Iris: accuracy={acc:.4f}")
print(f"  Class priors: {nb.class_prior_.round(3)}")

sub("4.4 Sequential Bayesian Updating (Beta-Binomial)")
alpha, beta_ = 1.0, 1.0    # uniform prior
data_stream  = [1, 1, 0, 1, 0, 1, 1, 1, 0, 1]   # coin flips
print("  Updating posterior after each flip:")
for i, x in enumerate(data_stream):
    alpha += x; beta_ += (1 - x)
    print(f"    After flip {i+1} ({x}): Beta({alpha:.0f},{beta_:.0f})  E[p]={alpha/(alpha+beta_):.3f}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 5 · Independence
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 5 · Independence")

sub("5.1 Event Independence: P(A∩B) = P(A)·P(B)")
rolls = np.random.randint(1, 7, 100_000)
A_ind = rolls <= 3          # {1,2,3}  P=0.5
B_ind = rolls % 2 == 0     # even      P=0.5
p_A_i  = A_ind.mean()
p_B_i  = B_ind.mean()
p_AB_i = (A_ind & B_ind).mean()   # should ≈ 0.25
product = p_A_i * p_B_i
print(f"  P(A)·P(B)={product:.4f}  P(A∩B)={p_AB_i:.4f}  diff={abs(product-p_AB_i):.4f} → independent ✓")

sub("5.2 Pairwise ≠ Mutual Independence (Counterexample)")
# Three events: all pairwise independent, but NOT mutually independent
# Ω = {HHH, HHT, HTH, HTT, THH, THT, TTH, TTT}
# A = {HHH,HHT,HTH,HTT}, B = {HHH,HHT,THH,THT}, C = {HHH,HTH,THH,TTH}
outcomes = list(itertools.product('HT', repeat=3))
def check_ind(ev_a, ev_b, omega):
    p_a = len(ev_a) / len(omega)
    p_b = len(ev_b) / len(omega)
    p_ab = len(ev_a & ev_b) / len(omega)
    return abs(p_a * p_b - p_ab) < 1e-9

omega_set = set(outcomes)
A3 = {o for o in outcomes if o[0] == 'H'}   # first is H
B3 = {o for o in outcomes if o[1] == 'H'}   # second is H
C3 = {o for o in outcomes if o[0] == o[1]}  # first == second

pairwise = all([check_ind(set(A3),set(B3),outcomes),
                check_ind(set(A3),set(C3),outcomes),
                check_ind(set(B3),set(C3),outcomes)])
p_abc  = len(set(A3) & set(B3) & set(C3)) / len(outcomes)
mutual = abs(p_abc - 0.5**3) < 1e-9
print(f"  Pairwise independent: {pairwise}")
print(f"  Mutually independent: {mutual}  (P(A∩B∩C)={p_abc:.4f} vs 0.125) — counterexample ✓")

sub("5.3 Conditional Independence (Markov Chain)")
# X_t ⊥ X_{t-2} | X_{t-1}  (Markov property)
T = 1000
states = [0]
for _ in range(T):
    states.append(1 if np.random.rand() < 0.7 else 0)
states = np.array(states)
# P(X_t|X_{t-1}) — empirical transition
trans = np.zeros((2, 2))
for i in range(1, len(states)):
    trans[states[i-1], states[i]] += 1
trans /= trans.sum(axis=1, keepdims=True)
print(f"  Markov transition matrix:\n    P(0→0)={trans[0,0]:.3f} P(0→1)={trans[0,1]:.3f}")
print(f"    P(1→0)={trans[1,0]:.3f} P(1→1)={trans[1,1]:.3f}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 6 · Random Variables
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 6 · Random Variables")

sub("6.2 CDF — Cumulative Distribution Function")
# F(x) = P(X ≤ x) for standard normal
normal_dist = torch.distributions.Normal(0.0, 1.0)
x_vals_cdf = torch.tensor([-2.0, -1.0, 0.0, 1.0, 1.96, 2.576])
cdfs = normal_dist.cdf(x_vals_cdf)
print("  Standard Normal CDF values:")
for x, f in zip(x_vals_cdf.tolist(), cdfs.tolist()):
    print(f"    Φ({x:6.3f}) = {f:.4f}")

# Properties: P(a < X ≤ b) = F(b) - F(a)
a_val, b_val = -1.0, 1.0
prob_interval = normal_dist.cdf(torch.tensor(b_val)) - \
                normal_dist.cdf(torch.tensor(a_val))
print(f"  P(-1 < Z ≤ 1) = {prob_interval:.4f}  (68-95-99.7 rule: 0.6827)")

sub("6.3 & 6.4 PMF / PDF Verification")
# PMF: Σ P(X=x) = 1
pmf = np.array([1/6]*6)
print(f"  Die PMF sums to: {pmf.sum():.4f} ✓")

# PDF: ∫ f(x)dx = 1  (numerical integration)
from scipy.integrate import quad
integrand = lambda x: stats.norm.pdf(x, 0, 1)
integral, _ = quad(integrand, -10, 10)
print(f"  Normal PDF integrates to: {integral:.6f} ✓")

# PDF can exceed 1: N(0, 0.1) at x=0
f_at_0 = stats.norm.pdf(0, 0, 0.1)
print(f"  N(0,0.1) PDF at x=0 = {f_at_0:.2f}  (>1, not a probability)")

sub("6.5 Quantile Function (Inverse CDF)")
# Q(p) = Φ⁻¹(p) for standard normal
quantile_probs = [0.025, 0.25, 0.50, 0.75, 0.975]
for p in quantile_probs:
    q = stats.norm.ppf(p)
    print(f"    Q({p}) = {q:.4f}")

sub("6.6 Functions of a Random Variable (Change of Variables)")
# Y = g(X) = X² where X ~ N(0,1)  → Y ~ χ²(1)
np.random.seed(42)
X_rv = np.random.normal(0, 1, 100_000)
Y_rv = X_rv**2
# Theoretical: chi-squared(1) — E[Y]=1, Var[Y]=2
print(f"  X~N(0,1): E[X²] = {Y_rv.mean():.4f}  (expected 1.0)")
print(f"  Var[X²] = {Y_rv.var():.4f}  (expected 2.0)")

# Log-normal: if Z ~ N(μ,σ²), W = e^Z → E[W] = e^(μ + σ²/2)
mu_ln, sigma_ln = 1.0, 0.5
Z_ln = np.random.normal(mu_ln, sigma_ln, 100_000)
W_ln = np.exp(Z_ln)
E_W_formula = math.exp(mu_ln + sigma_ln**2 / 2)
print(f"  Log-normal E[W] = {W_ln.mean():.4f}  formula = {E_W_formula:.4f} ✓")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 7 · Probability Distributions — Discrete
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 7 · Probability Distributions — Discrete")

sub("7.1 Bernoulli — Binary Classification")
p_bern = 0.7
bern_dist = torch.distributions.Bernoulli(p_bern)
s_bern    = bern_dist.sample((10000,))
print(f"  Bernoulli(p={p_bern}): E[X]=p={p_bern}  Var=p(1-p)={p_bern*(1-p_bern):.4f}")
print(f"  Empirical: mean={s_bern.mean():.4f}  var={s_bern.var():.4f}")

sub("7.2 Binomial — n Independent Trials")
n_bin, p_bin = 20, 0.6
binom_d = stats.binom(n_bin, p_bin)
# PMF: P(X=k) = C(n,k) p^k (1-p)^(n-k)
for k in [8, 12, 15]:
    pmf_k = binom_d.pmf(k)
    manual = math.comb(n_bin, k) * p_bin**k * (1-p_bin)**(n_bin-k)
    print(f"  P(X={k}) = {pmf_k:.5f}  manual = {manual:.5f} ✓")
print(f"  E[X]={n_bin*p_bin}  Var={n_bin*p_bin*(1-p_bin):.4f}")

sub("7.3 Categorical — Softmax Output")
pi_cat = torch.tensor([0.1, 0.3, 0.4, 0.2])
cat_dist = torch.distributions.Categorical(probs=pi_cat)
s_cat    = cat_dist.sample((10000,))
empirical_probs = torch.bincount(s_cat, minlength=4).float() / 10000
print(f"  Categorical probs: {pi_cat.tolist()}")
print(f"  Empirical probs  : {empirical_probs.tolist()}")

sub("7.4 Multinomial — Bag-of-Words")
n_mn, pi_mn = 10, np.array([0.2, 0.3, 0.5])   # 3 word types
mn_d = stats.multinomial(n_mn, pi_mn)
sample_mn = mn_d.rvs(1)[0]
print(f"  Multinomial(n={n_mn}, π={pi_mn}): sample={sample_mn}")
print(f"  E[X_k]={n_mn*pi_mn}  Var[X_k]={n_mn*pi_mn*(1-pi_mn).round(3)}")

sub("7.5 Poisson — Count Data (Mean=Variance)")
lam_p = 4.0
poisson_d = torch.distributions.Poisson(lam_p)
s_pois    = poisson_d.sample((20000,)).float()
# P(X=k) = λᵏ e^{-λ} / k!
for k in [0, 3, 4, 8]:
    p_k_formula = (lam_p**k * math.exp(-lam_p)) / math.factorial(k)
    p_k_scipy   = stats.poisson.pmf(k, lam_p)
    print(f"  P(X={k}) = {p_k_formula:.5f}  scipy={p_k_scipy:.5f} ✓")
print(f"  E[X]={s_pois.mean():.3f}  Var={s_pois.var():.3f}  (both → λ={lam_p} ✓)")

sub("7.6 Geometric — Memoryless Property")
p_geo = 0.3
geo_d = stats.geom(p_geo)
# Memoryless: P(X>m+n | X>m) = P(X>n)
m_geo, n_geo = 3, 5
p_gt_m_plus_n = geo_d.sf(m_geo + n_geo - 1)  # P(X > m+n)
p_gt_m        = geo_d.sf(m_geo - 1)            # P(X > m)
p_gt_n        = geo_d.sf(n_geo - 1)            # P(X > n)
conditional   = p_gt_m_plus_n / p_gt_m
print(f"  Memoryless: P(X>{m_geo+n_geo}|X>{m_geo})={conditional:.4f}  P(X>{n_geo})={p_gt_n:.4f} ✓")

sub("7.7 Negative Binomial — Overdispersed Counts")
r_nb, p_nb = 5, 0.4
E_nb  = r_nb / p_nb
Var_nb = r_nb * (1-p_nb) / p_nb**2
print(f"  NegBin(r={r_nb},p={p_nb}): E[X]={E_nb:.2f}  Var={Var_nb:.2f}  (Var>Mean → overdispersed)")

sub("7.8 Hypergeometric — Sampling Without Replacement")
# P(X=k) = C(K,k)·C(N-K,n-k) / C(N,n)
N_hg, K_hg, n_hg = 20, 8, 5    # pool=20, successes=8, draw=5
for k_hg in range(min(K_hg,n_hg)+1):
    if k_hg > n_hg or k_hg > K_hg or (n_hg-k_hg) > (N_hg-K_hg): continue
    p_hg = (math.comb(K_hg,k_hg)*math.comb(N_hg-K_hg,n_hg-k_hg)) / math.comb(N_hg,n_hg)
    print(f"    P(X={k_hg}) = {p_hg:.4f}")
E_hg  = n_hg * K_hg / N_hg
Var_hg = n_hg * (K_hg/N_hg) * ((N_hg-K_hg)/N_hg) * ((N_hg-n_hg)/(N_hg-1))
print(f"  E[X]={E_hg:.2f}  Var={Var_hg:.4f}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 8 · Probability Distributions — Continuous
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 8 · Probability Distributions — Continuous")

sub("8.1 Uniform — Weight Initialization (Glorot)")
a_u, b_u = -0.5, 0.5
unif = torch.distributions.Uniform(a_u, b_u)
s_u  = unif.sample((10000,))
E_u, Var_u = (a_u+b_u)/2, (b_u-a_u)**2/12
print(f"  Uniform({a_u},{b_u}): E={E_u}  Var={Var_u:.4f}")
print(f"  Empirical: mean={s_u.mean():.4f}  var={s_u.var():.4f}")
# Glorot uniform: limit = sqrt(6/(n_in+n_out))
n_in_g, n_out_g = 256, 128
glorot_limit = math.sqrt(6.0 / (n_in_g + n_out_g))
W_glorot = np.random.uniform(-glorot_limit, glorot_limit, (n_in_g, n_out_g))
print(f"  Glorot uniform init: limit={glorot_limit:.4f}  actual std={W_glorot.std():.4f}")

sub("8.2 Gaussian — Master Distribution")
mu_g, sigma_g = 3.0, 2.0
normal_t = torch.distributions.Normal(mu_g, sigma_g)
s_norm = normal_t.sample((50000,))
# 68-95-99.7 rule
within_1 = ((s_norm >= mu_g-sigma_g) & (s_norm <= mu_g+sigma_g)).float().mean()
within_2 = ((s_norm >= mu_g-2*sigma_g) & (s_norm <= mu_g+2*sigma_g)).float().mean()
within_3 = ((s_norm >= mu_g-3*sigma_g) & (s_norm <= mu_g+3*sigma_g)).float().mean()
print(f"  N({mu_g},{sigma_g}²): P(μ±1σ)={within_1:.4f}  P(μ±2σ)={within_2:.4f}  P(μ±3σ)={within_3:.4f}")

# Standardization Z = (X-μ)/σ
x_obs = 7.0
z_score = (x_obs - mu_g) / sigma_g
p_le_x  = stats.norm.cdf(z_score)
print(f"  P(X≤{x_obs}) = Φ(Z={(z_score):.2f}) = {p_le_x:.4f}")

sub("8.3 Multivariate Gaussian — Conditional Distribution")
# X = [X1, X2]  joint N(μ, Σ)
mu_mv  = torch.tensor([0.0, 0.0])
Sigma_mv = torch.tensor([[1.0, 0.8],
                         [0.8, 1.0]])
mvn_d  = torch.distributions.MultivariateNormal(mu_mv, Sigma_mv)
s_mv   = mvn_d.sample((10000,))

# Conditional: X1|X2=x2 ~ N(μ1 + Σ12·Σ22⁻¹(x2-μ2), Σ11-Σ12·Σ22⁻¹·Σ21)
x2_cond = 1.5
mu_cond  = 0 + 0.8/1.0*(x2_cond - 0)   # μ1|2
var_cond = 1.0 - 0.8**2/1.0             # σ²1|2
print(f"  X1|X2=1.5 ~ N({mu_cond:.2f}, {var_cond:.4f})")
# Verify empirically
mask = (s_mv[:,1] > 1.4) & (s_mv[:,1] < 1.6)
emp_mean = s_mv[mask, 0].mean()
emp_var  = s_mv[mask, 0].var()
print(f"  Empirical mean={emp_mean:.4f}  var={emp_var:.4f} ✓")

sub("8.4 Exponential — Memoryless")
lam_e = 2.0
exp_d = torch.distributions.Exponential(lam_e)
s_exp = exp_d.sample((100_000,))
# Memoryless: P(X>s+t|X>s) = P(X>t)
s_t, t_t = 1.0, 0.5
cond_prob = ((s_exp > s_t+t_t).float().sum() / (s_exp > s_t).float().sum())
p_gt_t    = (s_exp > t_t).float().mean()
print(f"  Memoryless: P(X>{s_t+t_t}|X>{s_t})={cond_prob:.4f}  P(X>{t_t})={p_gt_t:.4f} ✓")

sub("8.5 Gamma Distribution — Sum of Exponentials")
k_gm, theta_gm = 3.0, 2.0    # shape, scale
gm_d = torch.distributions.Gamma(k_gm, 1.0/theta_gm)
s_gm = gm_d.sample((10000,))
E_gm, Var_gm = k_gm*theta_gm, k_gm*theta_gm**2
print(f"  Gamma({k_gm},{theta_gm}): E={E_gm}  Var={Var_gm}")
print(f"  Empirical: mean={s_gm.mean():.4f}  var={s_gm.var():.4f}")

sub("8.6 Beta Distribution — Bayesian Prior on Probabilities")
alpha_b, beta_b = 3.0, 7.0
beta_d = torch.distributions.Beta(alpha_b, beta_b)
s_beta = beta_d.sample((10000,))
E_beta  = alpha_b / (alpha_b+beta_b)
Var_beta = alpha_b*beta_b / ((alpha_b+beta_b)**2*(alpha_b+beta_b+1))
print(f"  Beta({alpha_b},{beta_b}): E={E_beta:.4f}  Var={Var_beta:.5f}")
print(f"  Empirical:  mean={s_beta.mean():.4f}  var={s_beta.var():.5f}")

sub("8.7 Chi-Squared — Sum of Squared Normals")
k_chi = 5
Z_chi  = np.random.standard_normal((100_000, k_chi))
X_chi  = (Z_chi**2).sum(axis=1)    # χ²(k) = Σ Zᵢ²
chi2_d = stats.chi2(df=k_chi)
print(f"  χ²(k={k_chi}): E={k_chi}  Var={2*k_chi}")
print(f"  Empirical: mean={X_chi.mean():.4f}  var={X_chi.var():.4f}")

sub("8.8 Student's t — Heavy Tails")
nu_t = 3    # degrees of freedom
t_samp = np.random.standard_t(nu_t, 100_000)
# As ν→∞, t→N(0,1)
t_large = np.random.standard_t(100, 100_000)
print(f"  t(ν={nu_t}): Var = {nu_t/(nu_t-2):.4f}  empirical var={t_samp.var():.4f}")
print(f"  t(ν=100): approx N(0,1): empirical var={t_large.var():.4f} (→1)")

sub("8.9 Laplace — L1 Regularization Prior")
mu_l, b_l = 0.0, 1.0
lap_d = torch.distributions.Laplace(mu_l, b_l)
s_lap = lap_d.sample((10000,))
E_lap, Var_lap = mu_l, 2*b_l**2
print(f"  Laplace({mu_l},{b_l}): E={E_lap}  Var={Var_lap}")
print(f"  Empirical: mean={s_lap.mean():.4f}  var={s_lap.var():.4f}")

sub("8.10 Dirichlet — Prior over Categorical Distributions")
alphas_d = torch.tensor([2.0, 5.0, 3.0])
dirich   = torch.distributions.Dirichlet(alphas_d)
s_dir    = dirich.sample((5000,))
E_dir    = alphas_d / alphas_d.sum()
print(f"  Dirichlet({alphas_d.tolist()}): E[X]={E_dir.tolist()}")
print(f"  Empirical mean: {s_dir.mean(0).tolist()}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 9 · Joint, Marginal & Conditional Distributions
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 9 · Joint, Marginal & Conditional Distributions")

sub("9.1 Joint Distribution via 2D Histogram")
np.random.seed(42)
N_jt = 10_000
X_jt = np.random.normal(0, 1, N_jt)
Y_jt = 0.8 * X_jt + 0.6 * np.random.normal(0, 1, N_jt)
H2d, xe, ye = np.histogram2d(X_jt, Y_jt, bins=50, density=True)
dx, dy = xe[1]-xe[0], ye[1]-ye[0]
mass = H2d.sum() * dx * dy
print(f"  Joint PDF integrates to ≈ {mass:.4f} ✓")

sub("9.2 Marginal — Sum Out Other Variable")
marg_x = H2d.sum(axis=1) * dy    # marginalize over Y
marg_y = H2d.sum(axis=0) * dx    # marginalize over X
print(f"  Marginal P(X) integrates to: {(marg_x*dx).sum():.4f} ✓")
print(f"  Marginal P(Y) integrates to: {(marg_y*dy).sum():.4f} ✓")

sub("9.3 Conditional f(X|Y=y) = f(X,Y)/f(Y)")
# Empirical: X|Y≈0
mask_y = np.abs(Y_jt) < 0.1
X_given_Y0 = X_jt[mask_y]
# Theoretical: X|Y=0 ~ N(0, Σ11-Σ12Σ22⁻¹Σ21) for bivariate standard normal
print(f"  E[X|Y≈0]: empirical={X_given_Y0.mean():.4f}  theoretical≈0")
print(f"  Std[X|Y≈0]: empirical={X_given_Y0.std():.4f}  theoretical=sqrt(1-0.64)={math.sqrt(0.36):.4f}")

sub("9.4 Independence Test: f(X,Y)=f(X)f(Y)")
X_ind_test = np.random.normal(0,1,N_jt)
Y_ind_test = np.random.normal(0,1,N_jt)   # independent of X
corr_dep = np.corrcoef(X_jt, Y_jt)[0,1]
corr_ind = np.corrcoef(X_ind_test, Y_ind_test)[0,1]
print(f"  Corr(X,Y) dependent={corr_dep:.4f}  independent={corr_ind:.4f}")

sub("9.5 Mixture Model Marginal")
# p(x) = Σ_k π_k N(x|μ_k, σ²_k)  — GMM
gm_model = GaussianMixture(n_components=3, covariance_type='full', random_state=42)
X_gmm_data = np.concatenate([
    np.random.normal(-3, 1, 300),
    np.random.normal( 0, 0.5, 400),
    np.random.normal( 4, 1.5, 300)
]).reshape(-1, 1)
gm_model.fit(X_gmm_data)
print(f"  GMM weights: {gm_model.weights_.round(3)}")
print(f"  GMM means  : {gm_model.means_.ravel().round(3)}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 10 · Expectation
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 10 · Expectation")

sub("10.1 Discrete E[X] = Σ x·P(X=x)")
x_die = np.arange(1, 7)
p_die = np.ones(6) / 6
E_die = np.sum(x_die * p_die)
print(f"  Die E[X] = {E_die:.4f}  (expected 3.5)")

# Linearity: E[aX+b] = aE[X]+b
a_l, b_l_e = 3, -2
E_lin = a_l * E_die + b_l_e
E_lin_empirical = np.mean(a_l * np.random.choice(x_die, 100_000) + b_l_e)
print(f"  E[3X-2] = {E_lin:.4f}  empirical={E_lin_empirical:.4f} ✓")

sub("10.2 Tower Property: E[X] = E[E[X|Y]]")
groups = {0: np.random.normal(5, 1, 1000),
          1: np.random.normal(10, 1, 1000)}
all_vals = np.concatenate(list(groups.values()))
e_direct = all_vals.mean()
e_tower  = 0.5 * groups[0].mean() + 0.5 * groups[1].mean()
print(f"  E[X] direct={e_direct:.4f}  tower property={e_tower:.4f} ✓")

sub("10.3 Continuous E[X] = ∫ x·f(x)dx")
# E[X²] for N(0,1): should be 1 (= Var(X))
from scipy.integrate import quad as sci_quad
E_Xsq, _ = sci_quad(lambda x: x**2 * stats.norm.pdf(x), -10, 10)
print(f"  E[X²] for N(0,1) = {E_Xsq:.4f}  (= Var = 1.0 ✓)")

sub("10.4 Moments")
X_mom = np.random.normal(2, 3, 100_000)
mu_mom = X_mom.mean()
for k in [1, 2, 3, 4]:
    raw_moment     = np.mean(X_mom**k)
    central_moment = np.mean((X_mom - mu_mom)**k)
    print(f"  μ_{k} (raw)={raw_moment:.4f}  μ̃_{k} (central)={central_moment:.4f}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 11 · Variance & Covariance
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 11 · Variance & Covariance")

sub("11.1 Variance: Var(X) = E[X²] - (E[X])²")
X_v = np.random.normal(5, 3, 100_000)
var_def     = np.mean((X_v - X_v.mean())**2)    # definition
var_formula = np.mean(X_v**2) - X_v.mean()**2   # shortcut
print(f"  Var(X) definition={var_def:.4f}  formula={var_formula:.4f} ✓")

# Var(aX+b) = a²Var(X)
a_v, b_v = 4, -7
var_aXb_formula = a_v**2 * var_def
var_aXb_direct  = np.var(a_v*X_v + b_v)
print(f"  Var(4X-7): formula={var_aXb_formula:.4f}  direct={var_aXb_direct:.4f} ✓")

sub("11.2 Covariance: Cov(X,Y)=E[XY]-E[X]E[Y]")
X_c = np.random.normal(0,1,100_000)
Y_c = 3*X_c + np.random.normal(0,0.5,100_000)

cov_formula = np.mean(X_c*Y_c) - X_c.mean()*Y_c.mean()
cov_direct  = np.cov(X_c, Y_c)[0,1]
print(f"  Cov(X,Y) formula={cov_formula:.4f}  np.cov={cov_direct:.4f} ✓")

# Cov(aX+b, cY+d) = ac·Cov(X,Y)
a_c, c_c = 2, -3
cov_scaled_formula = a_c * c_c * cov_formula
cov_scaled_direct  = np.cov(a_c*X_c, c_c*Y_c)[0,1]
print(f"  Cov(2X,-3Y): formula={cov_scaled_formula:.4f}  direct={cov_scaled_direct:.4f} ✓")

sub("11.3 Pearson Correlation ρ ∈ [-1,1]")
rho = cov_formula / (X_c.std() * Y_c.std())
print(f"  ρ(X,Y) = {rho:.4f}")
rho_indep = np.corrcoef(X_c, np.random.normal(0,1,100_000))[0,1]
print(f"  ρ(X, independent Z) = {rho_indep:.4f}  (≈0 ✓)")

sub("11.4 Covariance Matrix Σ = E[(X-μ)(X-μ)ᵀ]")
X_mat = np.column_stack([X_c[:1000], Y_c[:1000],
                          np.random.normal(0,2,1000)])
Sigma_emp = np.cov(X_mat.T)
Sigma_man = (X_mat - X_mat.mean(0)).T @ (X_mat - X_mat.mean(0)) / (len(X_mat)-1)
print(f"  Covariance matrix shape: {Sigma_emp.shape}")
print(f"  Max element-wise diff (manual vs np.cov): {np.abs(Sigma_emp-Sigma_man).max():.2e} ✓")
print(f"  Cov(AX): A=[[1,2],[0,1]] → AΣAᵀ")
A_tr = np.array([[1,2,0],[0,1,0]])
cov_AX_formula = A_tr @ Sigma_emp @ A_tr.T
print(f"  AΣAᵀ:\n{cov_AX_formula.round(3)}")

sub("11.5 Law of Total Variance")
# Var(X) = E[Var(X|Y)] + Var(E[X|Y])
within_var  = 0.5*np.var(groups[0],ddof=1) + 0.5*np.var(groups[1],ddof=1)
between_var = np.var([groups[0].mean(), groups[1].mean()], ddof=0)
total_lv    = within_var + between_var
total_direct = np.var(all_vals, ddof=1)
print(f"  Total Var direct={total_direct:.4f}")
print(f"  Within+Between  ={total_lv:.4f} ✓")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 12 · Moment Generating Functions & Characteristic Functions
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 12 · MGF & Characteristic Functions")

sub("12.1 MGF: M_X(t)=E[e^tX]  →  E[X^k] = M_X^(k)(0)")
# For N(μ,σ²): M_X(t) = exp(μt + σ²t²/2)
mu_mgf, sigma_mgf = 2.0, 3.0
t_mgf = 0.01

def mgf_normal(t, mu, sigma):
    return math.exp(mu*t + 0.5*sigma**2*t**2)

# Numerical derivative at t=0 gives E[X]
dt = 1e-5
M_0_plus  = mgf_normal(dt, mu_mgf, sigma_mgf)
M_0_minus = mgf_normal(-dt, mu_mgf, sigma_mgf)
M_0       = mgf_normal(0, mu_mgf, sigma_mgf)

dM_dt    = (M_0_plus - M_0_minus) / (2*dt)      # M'(0) = E[X]
d2M_dt2  = (M_0_plus - 2*M_0 + M_0_minus)/dt**2  # M''(0) = E[X²]

print(f"  M'(0)  = {dM_dt:.4f}   E[X]={mu_mgf}")
print(f"  M''(0) = {d2M_dt2:.4f}  E[X²]={mu_mgf**2+sigma_mgf**2}")
print(f"  Var(X) = M''(0)-(M'(0))² = {d2M_dt2 - dM_dt**2:.4f}  true={sigma_mgf**2}")

sub("12.2 Independence: M_{X+Y}(t) = M_X(t)·M_Y(t)")
# Sum of two independent Gaussians is Gaussian
mu1, sig1 = 1.0, 2.0
mu2, sig2 = 3.0, 1.0
# E[X+Y] = μ1+μ2, Var(X+Y) = σ1²+σ2²
X_sum = np.random.normal(mu1, sig1, 100_000)
Y_sum = np.random.normal(mu2, sig2, 100_000)
Z_sum = X_sum + Y_sum
print(f"  X+Y: E={Z_sum.mean():.4f} ({mu1+mu2})  Var={Z_sum.var():.4f} ({sig1**2+sig2**2})")

sub("12.3 Cumulants & CGF: K_X(t) = log M_X(t)")
# κ1=μ, κ2=σ², κ3=skewness numerator, κ4=excess kurtosis numerator
X_cum = np.random.normal(mu_mgf, sigma_mgf, 100_000)
# Cumulants via scipy
kappa1 = stats.moment(X_cum, 1)
kappa2 = stats.moment(X_cum, 2)
kappa3 = stats.moment(X_cum, 3)
kappa4 = stats.moment(X_cum, 4) - 3*kappa2**2   # excess kurtosis numerator
print(f"  κ1=E[X]={kappa1+X_cum.mean():.4f}  κ2=Var={kappa2:.4f}  κ3={kappa3:.4f}  κ4={kappa4:.4f}")

sub("12.4 Characteristic Function: φ_X(t) = E[e^{itX}]")
# For N(0,1): φ(t) = e^{-t²/2}
t_cf = 1.0
phi_theory = math.exp(-t_cf**2 / 2)           # |φ_N(0,1)(1)| = e^{-0.5}
X_cf = np.random.standard_normal(50_000)
phi_empirical_real = np.mean(np.cos(t_cf * X_cf))   # Re[E[e^itX]]
phi_empirical_imag = np.mean(np.sin(t_cf * X_cf))   # Im[E[e^itX]]  should≈0
print(f"  φ(t=1): theory={phi_theory:.4f}  empirical real={phi_empirical_real:.4f}  imag={phi_empirical_imag:.4f}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 13 · Information Theory & Entropy
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 13 · Information Theory & Entropy")

def entropy(p, base=2):
    p = np.asarray(p, dtype=float)
    p = p[p > 0]
    return -np.sum(p * np.log(p) / np.log(base))

def cross_entropy(p, q, base=2):
    p, q = np.asarray(p), np.clip(np.asarray(q), 1e-12, 1)
    return -np.sum(p * np.log(q) / np.log(base))

def kl_divergence(p, q, base=2):
    p, q = np.asarray(p), np.clip(np.asarray(q), 1e-12, 1)
    mask = p > 0
    return np.sum(p[mask] * np.log(p[mask]/q[mask]) / np.log(base))

def jsd(p, q):
    m = 0.5*(p+q)
    return 0.5*kl_divergence(p,m) + 0.5*kl_divergence(q,m)

sub("13.1 Self-Information I(x) = -log P(x)")
p_rare, p_common = 0.01, 0.9
I_rare   = -math.log2(p_rare)
I_common = -math.log2(p_common)
print(f"  I(rare event,   p=0.01) = {I_rare:.2f} bits  ← high surprise")
print(f"  I(common event, p=0.90) = {I_common:.2f} bits  ← low surprise")

sub("13.2 Shannon Entropy H(X) = -Σ p·log(p)")
p_fair   = np.array([0.25]*4)
p_biased = np.array([0.7, 0.1, 0.1, 0.1])
p_det    = np.array([1.0, 0.0, 0.0, 0.0])
print(f"  H(uniform 4) = {entropy(p_fair):.4f} bits  (max = log₂4 = 2.0)")
print(f"  H(biased)    = {entropy(p_biased):.4f} bits")
print(f"  H(certain)   = {entropy(p_det):.4f} bits  (deterministic)")

# Chain rule: H(X,Y) = H(X) + H(Y|X)
p_XY = np.array([[0.2,0.1],[0.3,0.4]])   # joint distribution
p_X  = p_XY.sum(axis=1)
p_Y_given_X = p_XY / p_X[:,None]
H_X       = entropy(p_X)
H_Y_given_X = np.sum(p_X * np.array([entropy(p_Y_given_X[i])
                                      for i in range(len(p_X))]))
H_XY_sum  = H_X + H_Y_given_X
H_XY_direct = entropy(p_XY.ravel())
print(f"  Chain rule: H(X)+H(Y|X)={H_XY_sum:.4f}  H(X,Y)={H_XY_direct:.4f} ✓")

# Gaussian differential entropy: h(N(μ,σ²)) = 0.5·log(2πeσ²)
sigma_h = 2.0
h_gauss = 0.5 * math.log(2 * math.pi * math.e * sigma_h**2)
print(f"  h(N(0,{sigma_h}²)) = {h_gauss:.4f} nats")

sub("13.3 Cross-Entropy H(p,q) = -Σ p·log(q)")
p_true = np.array([0.4, 0.3, 0.2, 0.1])
q_pred = np.array([0.25, 0.25, 0.25, 0.25])  # model predicts uniform
H_p    = entropy(p_true)
H_pq   = cross_entropy(p_true, q_pred)
D_KL   = kl_divergence(p_true, q_pred)
print(f"  H(p)={H_p:.4f}  H(p,q)={H_pq:.4f}  KL={D_KL:.4f}")
print(f"  H(p,q) = H(p) + KL: {H_p+D_KL:.4f} ✓")

# TensorFlow classification cross-entropy loss
y_true_tf = tf.constant([[1,0,0,0]], dtype=tf.float32)
y_pred_tf = tf.constant([[0.25,0.25,0.25,0.25]], dtype=tf.float32)
ce_tf = tf.keras.losses.CategoricalCrossentropy()(y_true_tf, y_pred_tf)
print(f"  TF CE loss = {ce_tf.numpy():.4f}")

sub("13.4 KL Divergence D_KL(p||q) ≥ 0")
p_kl = np.array([0.4, 0.3, 0.2, 0.1])
q_kl = np.array([0.1, 0.2, 0.3, 0.4])
KL_pq = kl_divergence(p_kl, q_kl)
KL_qp = kl_divergence(q_kl, p_kl)
print(f"  D_KL(p||q)={KL_pq:.4f}  D_KL(q||p)={KL_qp:.4f}  (asymmetric!)")

# KL between two Gaussians: D_KL(N1||N2) closed form
mu1_kl, sig1_kl = 1.0, 1.0
mu2_kl, sig2_kl = 0.0, 2.0
KL_gauss = (math.log(sig2_kl/sig1_kl)
            + (sig1_kl**2 + (mu1_kl-mu2_kl)**2)/(2*sig2_kl**2)
            - 0.5)
print(f"  KL(N({mu1_kl},{sig1_kl}²)||N({mu2_kl},{sig2_kl}²)) = {KL_gauss:.4f}")

# VAE KL: D_KL(N(μ,σ²)||N(0,1)) = 0.5*(μ²+σ²-log σ²-1)
mu_vae, sig_vae = 0.5, 0.8
KL_vae = 0.5 * (mu_vae**2 + sig_vae**2 - math.log(sig_vae**2) - 1)
print(f"  VAE KL(N({mu_vae},{sig_vae}²)||N(0,1)) = {KL_vae:.4f}")

sub("13.5 Mutual Information I(X;Y) = H(X)-H(X|Y)")
p_xy = np.array([[0.2,0.1],[0.3,0.4]])
p_x_mi  = p_xy.sum(1)
p_y_mi  = p_xy.sum(0)
H_X_mi  = entropy(p_x_mi)
H_Y_mi  = entropy(p_y_mi)
H_XY_mi = entropy(p_xy.ravel())
MI_xy   = H_X_mi + H_Y_mi - H_XY_mi   # I(X;Y) = H(X)+H(Y)-H(X,Y)
print(f"  I(X;Y) = {MI_xy:.4f} bits  (=0 iff independent)")

# Feature selection via mutual information
from sklearn.datasets import make_classification
X_mi, y_mi = make_classification(n_samples=500, n_features=6,
                                   n_informative=3, random_state=42)
mi_scores = mutual_info_classif(X_mi, y_mi, random_state=42)
print(f"  MI feature scores: {mi_scores.round(4)}")

sub("13.6 Jensen-Shannon Divergence (GAN connection)")
p_jsd = np.array([0.4, 0.3, 0.2, 0.1])
q_jsd = np.array([0.1, 0.2, 0.3, 0.4])
JSD   = jsd(p_jsd, q_jsd)
print(f"  JSD(p||q) = {JSD:.4f}  (symmetric, ∈[0,log2])")
print(f"  GAN optimal: V(D*,G) = 2·JSD(p_data||p_g) - log4 = {2*JSD - math.log(4):.4f}")

sub("13.7 f-Divergences Family")
# KL, reverse-KL, Total Variation, Hellinger, Chi-squared
p_fd = np.array([0.4, 0.3, 0.2, 0.1])
q_fd = np.array([0.25,0.25,0.25,0.25])
r    = p_fd / q_fd                            # likelihood ratio
kl_fd  = np.sum(q_fd * r * np.log(r))        # f(t)=t·log(t)
tv_fd  = 0.5 * np.sum(q_fd * np.abs(r - 1))  # f(t)=|t-1|/2
hell_fd = np.sum(q_fd * (np.sqrt(r)-1)**2)   # f(t)=(√t-1)²
chi2_fd = np.sum(q_fd * (r-1)**2)            # f(t)=(t-1)²
print(f"  KL={kl_fd:.4f}  TV={tv_fd:.4f}  Hellinger={hell_fd:.4f}  χ²={chi2_fd:.4f}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 14 · Common Inequalities
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 14 · Common Inequalities")

sub("14.1 Markov's Inequality: P(X≥a) ≤ E[X]/a")
X_mk = np.abs(np.random.normal(0, 2, 100_000))   # non-negative
a_mk = 5.0
p_mc = (X_mk >= a_mk).mean()
bound = X_mk.mean() / a_mk
print(f"  P(X≥{a_mk}) = {p_mc:.4f}  ≤  E[X]/a = {bound:.4f} ✓")

sub("14.2 Chebyshev's Inequality: P(|X-μ|≥kσ) ≤ 1/k²")
mu_cheb = 0; sigma_cheb = 2
X_cheb = np.random.normal(mu_cheb, sigma_cheb, 200_000)
for k_cheb in [1, 2, 3]:
    p_actual = (np.abs(X_cheb - mu_cheb) >= k_cheb*sigma_cheb).mean()
    bound_cheb = 1.0 / k_cheb**2
    print(f"  k={k_cheb}: P(|X-μ|≥{k_cheb}σ)={p_actual:.4f}  ≤  1/k²={bound_cheb:.4f} ✓")
print("  (Normal is much tighter than Chebyshev — it's a universal bound)")

sub("14.3 Jensen's Inequality: φ(E[X]) ≤ E[φ(X)] for convex φ")
X_jen = np.random.exponential(2.0, 100_000)
# φ(x) = x² is convex: (E[X])² ≤ E[X²]
lhs_jen = X_jen.mean()**2          # (E[X])²
rhs_jen = (X_jen**2).mean()        # E[X²]
print(f"  Convex x²: (E[X])²={lhs_jen:.4f} ≤ E[X²]={rhs_jen:.4f} ✓")
# φ(x) = log(x) is concave: log(E[X]) ≥ E[log X]
log_EX    = math.log(X_jen.mean())
E_log_X   = np.log(X_jen).mean()
print(f"  Concave log: log(E[X])={log_EX:.4f} ≥ E[log X]={E_log_X:.4f} ✓")

# VAE ELBO derivation via Jensen
print("  VAE ELBO: log p(x) = log E_q[p(x,z)/q(z)] ≥ E_q[log p(x,z)/q(z)] = ELBO")

sub("14.4 Cauchy-Schwarz: (E[XY])² ≤ E[X²]·E[Y²]")
X_cs = np.random.normal(0,1,100_000)
Y_cs = 2*X_cs + np.random.normal(0,0.5,100_000)
lhs_cs = np.mean(X_cs*Y_cs)**2
rhs_cs = np.mean(X_cs**2) * np.mean(Y_cs**2)
print(f"  (E[XY])²={lhs_cs:.4f} ≤ E[X²]·E[Y²]={rhs_cs:.4f} ✓")

sub("14.5 Hoeffding's Inequality — Generalization Bounds")
# P(X̄ - E[X̄] ≥ t) ≤ exp(-2n²t² / Σ(bᵢ-aᵢ)²)
# All Xᵢ ∈ [0,1], so bᵢ-aᵢ=1
n_hf, t_hf = 1000, 0.05
bound_hf = math.exp(-2 * n_hf**2 * t_hf**2 / (n_hf * 1**2))
print(f"  Hoeffding bound (n={n_hf}, t={t_hf}): P(X̄-E[X̄]≥{t_hf}) ≤ {bound_hf:.6f}")

# Gibbs' inequality: KL(p||q) ≥ 0 (proved via Jensen)
p_g, q_g = np.array([0.4,0.3,0.2,0.1]), np.array([0.3,0.3,0.2,0.2])
print(f"  Gibbs' (KL≥0): D_KL(p||q)={kl_divergence(p_g,q_g):.4f} ✓")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 15 · Limit Theorems
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 15 · Limit Theorems")

sub("15.1 Law of Large Numbers (Weak & Strong)")
# X̄_n → μ as n → ∞  (exponential distribution, μ=2)
mu_lln = 2.0
for n_lln in [10, 100, 1000, 10_000, 100_000]:
    x_bar = np.random.exponential(mu_lln, n_lln).mean()
    print(f"  n={n_lln:>7}: X̄_n={x_bar:.5f}  error={abs(x_bar-mu_lln):.5f}")

print("  ERM: Empirical risk → true risk as n→∞ (justifies gradient descent)")

sub("15.2 Central Limit Theorem: √n(X̄-μ)/σ → N(0,1)")
# ANY distribution → sampling distribution of mean is normal
distributions = {
    "Exponential(2)": lambda: np.random.exponential(2, 50),
    "Bernoulli(0.3)": lambda: np.random.binomial(1, 0.3, 50),
    "Uniform(0,1)":   lambda: np.random.uniform(0, 1, 50),
}
print("  Normality test of sample means (p>0.05 = consistent with normality):")
for name, sampler in distributions.items():
    means = [sampler().mean() for _ in range(2000)]
    _, p_sw = stats.shapiro(means[:500])
    print(f"    {name}: p={p_sw:.4f}")

# SGD: mini-batch gradients are approximately Gaussian
full_grads = np.random.laplace(0.5, 2.0, 100_000)   # true gradient: Laplace
batch_means = [full_grads[np.random.choice(len(full_grads),64)].mean()
               for _ in range(1000)]
_, p_sgd = stats.shapiro(batch_means[:500])
print(f"  Mini-batch (bs=64) of Laplace gradients: p={p_sgd:.4f} (CLT makes it Gaussian)")

sub("15.3 Multivariate CLT")
mu_mv_clt = np.array([1.0, 2.0])
Sigma_mv_clt = np.array([[1.0,0.5],[0.5,2.0]])
n_mv_clt = 100
sample_means_mv = np.array([
    np.random.multivariate_normal(mu_mv_clt, Sigma_mv_clt, n_mv_clt).mean(0)
    for _ in range(5000)
])
print(f"  Multivariate CLT: mean of means={sample_means_mv.mean(0).round(4)}")
print(f"  Expected Var of mean (Σ/n): {(Sigma_mv_clt/n_mv_clt).diagonal().round(4)}")
print(f"  Empirical Var of mean     : {np.var(sample_means_mv,axis=0).round(4)} ✓")

sub("15.4 Delta Method: g(X̄) → N(g(μ), [g'(μ)]²σ²/n)")
# g(x) = log(x), X ~ Exponential(λ=0.5), μ=2, σ²=4, g'(μ)=1/μ
lam_dm = 0.5
mu_dm, sigma2_dm = 1/lam_dm, 1/lam_dm**2
n_dm = 100
def g_dm(x): return np.log(x)
def g_prime(x): return 1/x

delta_var = (g_prime(mu_dm))**2 * sigma2_dm / n_dm
log_means = [np.log(np.random.exponential(1/lam_dm, n_dm).mean())
             for _ in range(10_000)]
print(f"  Delta method: g(X̄) Var theory={delta_var:.6f}  empirical={np.var(log_means):.6f}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 16 · Bayesian Probability & Inference
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 16 · Bayesian Probability & Inference")

sub("16.1 Bayesian Framework — Posterior Predictive")
# After observing k heads in n flips → Beta posterior → predict next flip
alpha_bp, beta_bp = 2.0, 2.0   # prior
k_obs, n_obs = 7, 10
alpha_post = alpha_bp + k_obs
beta_post  = beta_bp + (n_obs - k_obs)
# Posterior predictive: P(next=H) = alpha_post/(alpha_post+beta_post)
p_next_H = alpha_post / (alpha_post + beta_post)
print(f"  Posterior Beta({alpha_post},{beta_post}): E[p]={p_next_H:.4f}")
print(f"  MLE: p̂={k_obs/n_obs:.4f}  Posterior mean shrinks toward prior")

sub("16.2 Conjugate Priors Table")
conjugates = {
    "Bernoulli/Binomial": ("Beta(α,β)", f"Beta({alpha_post:.0f},{beta_post:.0f})"),
    "Poisson":  ("Gamma(α,β)", "Gamma(α+Σxᵢ, β+n)"),
    "Gaussian": ("Gaussian",   "Gaussian"),
    "Multinomial": ("Dirichlet", "Dirichlet(α+counts)"),
}
print(f"  {'Likelihood':<20} {'Prior':<15} {'Posterior'}")
for lik, (pri, post) in conjugates.items():
    print(f"  {lik:<20} {pri:<15} {post}")

# Poisson-Gamma conjugate
alpha_g_conj, beta_g_conj = 2.0, 1.0     # Gamma prior on λ
x_pois_obs = np.random.poisson(3.0, 20)   # 20 Poisson observations
alpha_g_post = alpha_g_conj + x_pois_obs.sum()
beta_g_post  = beta_g_conj + len(x_pois_obs)
print(f"\n  Poisson-Gamma: observed sum={x_pois_obs.sum()}")
print(f"  Prior: Gamma({alpha_g_conj},{beta_g_conj})  → Posterior E[λ]={alpha_g_post/beta_g_post:.4f}  (MLE={x_pois_obs.mean():.4f})")

sub("16.3 ELBO — Variational Inference")
# log p(x) = ELBO + KL(q||p)  → ELBO is lower bound
# ELBO = E_q[log p(x|z)] - KL(q(z)||p(z))
# Simulate: encoder outputs μ, logσ²
mu_enc    = torch.tensor([0.3, -0.2, 0.5])
logvar_enc = torch.tensor([-0.5, 0.1, -0.3])
sigma_enc  = torch.exp(0.5 * logvar_enc)

# KL(N(μ,σ²)||N(0,1)) = 0.5·Σ(μ²+σ²-logσ²-1)
KL_enc = 0.5 * torch.sum(mu_enc**2 + sigma_enc**2 - logvar_enc - 1)
print(f"  VAE KL term (3D latent): {KL_enc.item():.4f}")

# Reparameterization trick: z = μ + σ·ε,  ε ~ N(0,I)
eps = torch.randn_like(mu_enc)
z   = mu_enc + sigma_enc * eps
print(f"  Reparameterized z = {z.detach().numpy().round(4)}")

sub("16.4 Bayesian Updating — Online Learning")
# Prior → observe data → posterior = new prior
alpha_upd, beta_upd = 1.0, 1.0
stream = np.random.binomial(1, 0.65, 20)
print("  Online Bayesian updating:")
for i, x in enumerate(stream[:5]):
    alpha_upd += x; beta_upd += (1-x)
    print(f"    Step {i+1}: Beta({alpha_upd:.0f},{beta_upd:.0f}) → E[p]={alpha_upd/(alpha_upd+beta_upd):.3f}")

sub("16.5 Bayes Factor — Model Comparison")
# BF12 = p(D|M1)/p(D|M2)
# Simple example: M1=fair coin (p=0.5), M2=biased (p=0.7)
n_bf, k_bf = 15, 11   # 11 heads in 15 flips
p_D_M1 = stats.binom.pmf(k_bf, n_bf, 0.5)
p_D_M2 = stats.binom.pmf(k_bf, n_bf, 0.7)
BF_12  = p_D_M2 / p_D_M1
print(f"  Observed {k_bf}/{n_bf} heads: BF(biased/fair) = {BF_12:.2f} → {'evidence for biased' if BF_12>1 else 'evidence for fair'}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 17 · Probabilistic Graphical Models
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 17 · Probabilistic Graphical Models")

sub("17.1 Bayesian Network — Joint Factorization")
# Simple Bayesian Net: Rain→Wet  Traffic→Late  Rain→Traffic
# p(Rain,Traffic,Wet,Late) = p(Rain)·p(Traffic|Rain)·p(Wet|Rain)·p(Late|Traffic)
p_rain = 0.3
p_traffic_rain = {True: 0.8, False: 0.4}
p_wet_rain     = {True: 0.9, False: 0.1}
p_late_traffic = {True: 0.7, False: 0.2}

# Compute joint and marginal by enumeration
total = 0; p_late_total = 0
for rain in [True, False]:
    for traffic in [True, False]:
        for wet in [True, False]:
            for late in [True, False]:
                p_joint = (p_rain if rain else 1-p_rain) * \
                          (p_traffic_rain[rain] if traffic else 1-p_traffic_rain[rain]) * \
                          (p_wet_rain[rain] if wet else 1-p_wet_rain[rain]) * \
                          (p_late_traffic[traffic] if late else 1-p_late_traffic[traffic])
                total += p_joint
                if late: p_late_total += p_joint
print(f"  Joint sums to: {total:.6f} ✓")
print(f"  P(Late) marginal = {p_late_total:.4f}")

sub("17.2 Markov Random Field — Energy Model")
# Ising-like MRF: p(x) ∝ exp(-E(x)),  E(x) = -ΣΣ J_ij x_i x_j
# Compute partition function for 2-node MRF
def mrf_energy(x1, x2, J=0.5):
    return -J * x1 * x2

states_mrf = list(itertools.product([-1,1], repeat=2))
energies = [mrf_energy(*s) for s in states_mrf]
Z = sum(math.exp(-e) for e in energies)
probs_mrf = [math.exp(-e)/Z for e in energies]
print("  2-node Ising MRF:")
for (s,e,p) in zip(states_mrf, energies, probs_mrf):
    print(f"    x={s}  E={e:.2f}  p={p:.4f}")

sub("17.3 Hidden Markov Model — Viterbi (simplified)")
# States: {S1, S2},  Observations: {A, B}
A_hmm = np.array([[0.7, 0.3],    # transition: A[i,j] = P(z_{t+1}=j|z_t=i)
                  [0.4, 0.6]])
B_hmm = np.array([[0.9, 0.1],    # emission: B[i,j] = P(x_t=j|z_t=i)
                  [0.2, 0.8]])
pi_hmm = np.array([0.6, 0.4])    # initial state probabilities

obs_seq = [0, 1, 0, 1]           # sequence of observations
T_hmm   = len(obs_seq)

# Viterbi algorithm
viterbi = np.zeros((T_hmm, 2))
psi     = np.zeros((T_hmm, 2), dtype=int)

viterbi[0] = np.log(pi_hmm) + np.log(B_hmm[:, obs_seq[0]])
for t in range(1, T_hmm):
    for j in range(2):
        trans_prob = viterbi[t-1] + np.log(A_hmm[:, j])
        psi[t, j]  = np.argmax(trans_prob)
        viterbi[t, j] = np.max(trans_prob) + np.log(B_hmm[j, obs_seq[t]])

# Backtrack
best_path = np.zeros(T_hmm, dtype=int)
best_path[-1] = np.argmax(viterbi[-1])
for t in range(T_hmm-2, -1, -1):
    best_path[t] = psi[t+1, best_path[t+1]]
print(f"  HMM Viterbi best path: {best_path.tolist()}  (most likely hidden states)")
print(f"  Log-probability: {viterbi[-1, best_path[-1]]:.4f}")

sub("17.4 Gaussian Mixture Model — EM")
np.random.seed(42)
X_gm = np.concatenate([
    np.random.normal(-2, 0.8, 200),
    np.random.normal( 2, 0.8, 300),
]).reshape(-1,1)
gm_em = GaussianMixture(n_components=2, covariance_type='full', random_state=42)
gm_em.fit(X_gm)
print(f"  GMM weights: {gm_em.weights_.round(4)}")
print(f"  GMM means  : {gm_em.means_.ravel().round(4)}")
print(f"  GMM stds   : {np.sqrt(gm_em.covariances_.ravel()).round(4)}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 18 · Exponential Family
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 18 · Exponential Family")

sub("18.1 Definition: p(x|η) = h(x)·exp(η·T(x) - A(η))")
# Bernoulli: η=log(p/(1-p)),  T(x)=x,  A(η)=log(1+e^η)
def bernoulli_expfam(x, p):
    eta = math.log(p / (1-p))        # natural parameter (logit)
    T_x = x                           # sufficient statistic
    h_x = 1                           # base measure
    A_eta = math.log(1 + math.exp(eta))  # log-partition (softplus)
    log_p = math.log(h_x) + eta*T_x - A_eta
    return math.exp(log_p)

p_bern_ef = 0.7
print(f"  Bernoulli(p={p_bern_ef}) via exp-family:")
for x_ef in [0, 1]:
    print(f"    P(X={x_ef}) expfam={bernoulli_expfam(x_ef, p_bern_ef):.4f}"
          f"  direct={p_bern_ef**x_ef*(1-p_bern_ef)**(1-x_ef):.4f} ✓")

# Poisson: η=log(λ),  T(x)=x,  h(x)=1/x!,  A(η)=e^η
lam_ef = 3.0
eta_pois = math.log(lam_ef)
for k_ef in [0, 1, 2, 3, 5]:
    A_eta_p = math.exp(eta_pois)   # = λ
    log_p = -gammaln(k_ef+1) + eta_pois*k_ef - A_eta_p
    p_expfam = math.exp(log_p)
    p_direct = stats.poisson.pmf(k_ef, lam_ef)
    print(f"  Poisson(λ={lam_ef}) P(X={k_ef}): expfam={p_expfam:.5f}  scipy={p_direct:.5f} ✓")

sub("18.2 Key Property: E[T(X)] = ∇A(η)  and  Var via ∇²A(η)")
# For Gaussian: η=(μ/σ², -1/2σ²), T(x)=(x,x²)
# ∇A(η) = E[(x,x²)] = (μ, μ²+σ²)
mu_ef, sig2_ef = 3.0, 4.0
eta1 = mu_ef / sig2_ef
eta2 = -1 / (2*sig2_ef)
# Partial derivatives of A(η)
E_x   = -eta1 / (2*eta2)          # should = μ
E_x2  = eta1**2/(4*eta2**2) - 1/(2*eta2)  # should = μ²+σ²
print(f"  Gaussian exp-family: E[X]={E_x:.4f} (μ={mu_ef})")
print(f"  E[X²]={E_x2:.4f} (μ²+σ²={mu_ef**2+sig2_ef:.4f})")

sub("18.3 Maximum Entropy — Exponential Family is MaxEnt")
# Uniform maximizes entropy with no constraints
# Gaussian maximizes entropy with fixed mean and variance
# Exponential maximizes entropy with fixed mean (non-negative support)
x_grid = np.linspace(0.01, 10, 1000)
lambda_me = 1/2.0    # E[X]=2
f_exp = lambda_me * np.exp(-lambda_me * x_grid)
h_exp = -np.trapz(f_exp * np.log(f_exp + 1e-15), x_grid)
print(f"  Differential entropy of Exp(λ=0.5): {h_exp:.4f} nats")
print(f"  Analytical: 1-log(λ) = {1-math.log(lambda_me):.4f} ✓")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 19 · Maximum Likelihood & MAP Estimation
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 19 · MLE & MAP Estimation")

sub("19.1 MLE — Log-Likelihood Maximization")
np.random.seed(42)
# MLE for Gaussian parameters: μ̂=x̄, σ̂²=Σ(xᵢ-x̄)²/n
true_mu_mle, true_sig_mle = 5.0, 2.0
data_mle = np.random.normal(true_mu_mle, true_sig_mle, 1000)

mu_hat    = data_mle.mean()
sigma2_hat = np.var(data_mle, ddof=0)    # MLE (biased)
sigma2_unb = np.var(data_mle, ddof=1)   # unbiased
print(f"  Gaussian MLE: μ̂={mu_hat:.4f}  σ̂²={sigma2_hat:.4f}  (biased)")
print(f"  Unbiased s²={sigma2_unb:.4f}  (uses n-1)")

# Manual log-likelihood surface for μ
log_likelihoods = []
mu_grid = np.linspace(4, 6, 200)
for mu_test in mu_grid:
    ll = np.sum(stats.norm.logpdf(data_mle, mu_test, true_sig_mle))
    log_likelihoods.append(ll)
mu_best = mu_grid[np.argmax(log_likelihoods)]
print(f"  Grid search MLE: μ̂={mu_best:.4f}  analytic: {mu_hat:.4f} ✓")

# MLE for Bernoulli
flips_mle = np.random.binomial(1, 0.6, 500)
p_mle = flips_mle.mean()
print(f"  Bernoulli MLE: p̂={p_mle:.4f}  (true p=0.6)")

sub("19.2 MLE = Minimizing KL(p̂_data || p_θ)")
# MLE ≡ arg min D_KL(p_emp || p_θ)
# Shown via: max Σlog p(xᵢ|θ) = min -Σlog p(xᵢ|θ) = min H(p̂,p_θ) = min KL(p̂||p_θ)+const
p_emp = np.histogram(data_mle, bins=50, density=True)[0]
p_emp = p_emp / p_emp.sum()
x_bins = np.linspace(data_mle.min(), data_mle.max(), 50)
dx_bin = x_bins[1]-x_bins[0]
for mu_test in [4.5, mu_hat, 5.5]:
    p_model = stats.norm.pdf(x_bins, mu_test, true_sig_mle)
    p_model = p_model / p_model.sum()
    kl = kl_divergence(p_emp+1e-10, p_model+1e-10)
    print(f"  KL(p̂||p_θ) at μ={mu_test:.2f}: {kl:.4f}  ← min at MLE ✓")

sub("19.3 MAP — MLE + Log Prior (Regularization)")
np.random.seed(0)
X_map = np.random.randn(80, 5)
w_true_map = np.array([1.0, 2.0, 0.0, -1.5, 0.5])
y_map = X_map @ w_true_map + np.random.randn(80) * 0.5

from sklearn.linear_model import LinearRegression
ols   = LinearRegression(fit_intercept=False).fit(X_map, y_map)
ridge = Ridge(alpha=2.0, fit_intercept=False).fit(X_map, y_map)
lasso = Lasso(alpha=0.2, fit_intercept=False).fit(X_map, y_map)

print(f"  True β :   {w_true_map}")
print(f"  OLS    :   {ols.coef_.round(4)}")
print(f"  Ridge  :   {ridge.coef_.round(4)}  ← Gaussian prior (L2)")
print(f"  Lasso  :   {lasso.coef_.round(4)}  ← Laplace prior  (L1, sparse)")

sub("19.4 EM Algorithm — Gaussian Mixture")
# E-step: r_ik = π_k N(x|μ_k,Σ_k) / Σ_j π_j N(x|μ_j,Σ_j)
# M-step: update π_k, μ_k, Σ_k
np.random.seed(0)
X_em = np.concatenate([np.random.normal(-2,1,200), np.random.normal(3,1,200)])

# Manual EM for 1D GMM (2 components)
pi_em = np.array([0.5, 0.5])
mu_em = np.array([-1.0, 1.0])   # init far from truth
sig_em = np.array([1.0, 1.0])

for iteration in range(20):
    # E-step: compute responsibilities
    r = np.column_stack([
        pi_em[k] * stats.norm.pdf(X_em, mu_em[k], sig_em[k])
        for k in range(2)
    ])
    r /= r.sum(axis=1, keepdims=True)
    # M-step: update parameters
    N_k = r.sum(0)
    pi_em  = N_k / len(X_em)
    mu_em  = (r * X_em[:,None]).sum(0) / N_k
    sig_em = np.sqrt(((r * (X_em[:,None]-mu_em)**2).sum(0)) / N_k)

print(f"  EM GMM converged: π={pi_em.round(3)}  μ={mu_em.round(3)}  σ={sig_em.round(3)}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 20 · Probabilistic Models in ML/DL
# ──────────────────────────────────────────────────────────────────────────────
header("SECTION 20 · Probabilistic Models in ML/DL")

sub("20.1 Logistic Regression — P(y=1|x) = σ(wᵀx)")
from sklearn.datasets import make_classification
X_lr, y_lr = make_classification(n_samples=500, n_features=4,
                                  n_informative=3, random_state=42)
log_reg = LogisticRegression(random_state=42).fit(X_lr, y_lr)
probs_lr = log_reg.predict_proba(X_lr[:5])
print(f"  Logistic Regression probabilities (first 5):\n  {probs_lr.round(4)}")

# Manual sigmoid: σ(z) = 1/(1+e^{-z})
z_logit = np.array([-3, -1, 0, 1, 3], dtype=float)
sigma_z  = 1 / (1 + np.exp(-z_logit))
print(f"  σ({z_logit}) = {sigma_z.round(4)}")

# BCE Loss: L = -[y log p̂ + (1-y) log(1-p̂)]
p_hat = log_reg.predict_proba(X_lr)[:,1]
bce   = -np.mean(y_lr * np.log(p_hat+1e-9) + (1-y_lr)*np.log(1-p_hat+1e-9))
print(f"  Binary cross-entropy = {bce:.4f}")

sub("20.2 Softmax & Log-Sum-Exp Trick")
logits = np.array([2.0, 1.0, 0.5, 3.0])

# Naive softmax (numerically unstable for large logits)
def softmax_naive(z):
    return np.exp(z) / np.exp(z).sum()

# Numerically stable: log-sum-exp trick
def softmax_stable(z):
    z_max = z.max()
    shifted = z - z_max
    return np.exp(shifted) / np.exp(shifted).sum()

def log_sum_exp(z):
    z_max = z.max()
    return z_max + np.log(np.exp(z - z_max).sum())

probs_naive  = softmax_naive(logits)
probs_stable = softmax_stable(logits)
print(f"  Softmax (naive)  : {probs_naive.round(4)}")
print(f"  Softmax (stable) : {probs_stable.round(4)}")
print(f"  Log-sum-exp      : {log_sum_exp(logits):.4f}")

# TF softmax + cross-entropy
logits_tf = tf.constant([[2.0, 1.0, 0.5, 3.0]])
y_true_tf = tf.constant([[0, 0, 0, 1]])
ce_tf_sm  = tf.keras.losses.CategoricalCrossentropy(from_logits=True)(
    tf.cast(y_true_tf, tf.float32), logits_tf)
print(f"  TF CE from logits: {ce_tf_sm.numpy():.4f}")

sub("20.3 Gaussian Discriminant Analysis (LDA/QDA)")
# LDA: shared Σ → linear boundary  |  QDA: per-class Σ → quadratic
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis

X_gda, y_gda = make_classification(n_samples=400, n_features=2, n_informative=2,
                                     n_redundant=0, random_state=42)
lda = LinearDiscriminantAnalysis().fit(X_gda, y_gda)
qda = QuadraticDiscriminantAnalysis().fit(X_gda, y_gda)
print(f"  LDA accuracy: {lda.score(X_gda, y_gda):.4f}")
print(f"  QDA accuracy: {qda.score(X_gda, y_gda):.4f}")
print(f"  LDA class means: {lda.means_.round(3)}")

sub("20.4 Gaussian Process — Kernel Regression")
def rbf_kernel(X1, X2, sigma=1.0, length_scale=1.0):
    """k(x,x') = σ²·exp(-||x-x'||²/2ℓ²)"""
    sq_dist = np.sum((X1[:,None] - X2[None,:])**2, axis=-1)
    return sigma**2 * np.exp(-sq_dist / (2*length_scale**2))

np.random.seed(42)
X_train_gp = np.linspace(-3, 3, 10)[:, None]
y_train_gp  = np.sin(X_train_gp.ravel()) + np.random.randn(10)*0.1
X_test_gp   = np.linspace(-4, 4, 100)[:, None]

sigma2_noise = 0.01
K_XX  = rbf_kernel(X_train_gp, X_train_gp) + sigma2_noise*np.eye(10)
K_Xs  = rbf_kernel(X_test_gp, X_train_gp)
K_ss  = rbf_kernel(X_test_gp, X_test_gp)

# GP posterior: f*|y ~ N(μ*, Σ*)
# μ* = K_*X (K_XX + σ²I)⁻¹ y
# Σ* = K_** - K_*X (K_XX + σ²I)⁻¹ K_X*
K_inv  = np.linalg.inv(K_XX)
mu_gp  = K_Xs @ K_inv @ y_train_gp
var_gp = np.diag(K_ss - K_Xs @ K_inv @ K_Xs.T)

print(f"  GP Regression: train MSE={np.mean((mu_gp[:10].ravel()-y_train_gp.ravel()[:10])**2):.6f}")
print(f"  Avg predictive std: {np.sqrt(var_gp.mean()):.4f}")

sub("20.5 Variational Autoencoder (VAE) — ELBO")
class VAE(nn.Module):
    def __init__(self, input_dim=20, latent_dim=4):
        super().__init__()
        self.encoder = nn.Sequential(nn.Linear(input_dim, 16), nn.ReLU())
        self.fc_mu     = nn.Linear(16, latent_dim)
        self.fc_logvar = nn.Linear(16, latent_dim)
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, 16), nn.ReLU(),
            nn.Linear(16, input_dim), nn.Sigmoid())

    def reparameterize(self, mu, logvar):
        # z = μ + σ·ε,  ε~N(0,I)  — reparameterization trick
        eps = torch.randn_like(mu)
        return mu + torch.exp(0.5*logvar) * eps

    def forward(self, x):
        h      = self.encoder(x)
        mu_enc = self.fc_mu(h)
        logvar = self.fc_logvar(h)
        z      = self.reparameterize(mu_enc, logvar)
        x_rec  = self.decoder(z)
        return x_rec, mu_enc, logvar

def vae_loss(x_rec, x, mu, logvar):
    # ELBO = Reconstruction - KL(q||p)
    # Reconstruction: binary cross-entropy
    recon = nn.BCELoss(reduction='sum')(x_rec, x)
    # KL: D_KL(N(μ,σ²)||N(0,I)) = 0.5·Σ(μ²+σ²-logσ²-1)
    kl    = -0.5 * torch.sum(1 + logvar - mu**2 - torch.exp(logvar))
    return recon + kl, recon, kl

# Quick training run
vae_model = VAE(input_dim=20, latent_dim=4)
optimizer_vae = torch.optim.Adam(vae_model.parameters(), lr=1e-3)
X_vae = torch.rand(200, 20)   # synthetic data

for epoch in range(50):
    optimizer_vae.zero_grad()
    x_rec, mu_out, logvar_out = vae_model(X_vae)
    loss_vae, recon_l, kl_l = vae_loss(x_rec, X_vae, mu_out, logvar_out)
    loss_vae.backward()
    optimizer_vae.step()

print(f"  VAE final ELBO: total={loss_vae.item():.2f}  recon={recon_l.item():.2f}  KL={kl_l.item():.2f}")

sub("20.6 GAN — Minimax Game")
# min_G max_D E[log D(x)] + E[log(1-D(G(z)))]
# Optimal D*(x) = p_data(x) / (p_data(x)+p_g(x))
# GAN objective at optimum = 2·JSD(p_data||p_g) - log4
p_data_gan = np.array([0.5, 0.3, 0.2])   # real data distribution
p_gen_gan  = np.array([0.4, 0.4, 0.2])   # generator distribution
jsd_gan    = jsd(p_data_gan, p_gen_gan)
v_star     = 2*jsd_gan - math.log(4)
print(f"  GAN JSD(p_data||p_g) = {jsd_gan:.4f}")
print(f"  V(D*,G) = 2·JSD - log4 = {v_star:.4f}")

sub("20.7 Normalizing Flows — Log-Prob via Change of Variables")
# log p_X(x) = log p_Z(f(x)) + log|det J_f(x)|
# Example: 1D linear flow z = (x-μ)/σ
def flow_log_prob(x_flow, mu_f=2.0, sigma_f=1.5):
    z       = (x_flow - mu_f) / sigma_f
    log_pz  = -0.5*z**2 - 0.5*math.log(2*math.pi)    # log N(0,1)
    log_det = -math.log(abs(sigma_f))                  # log|df/dx|⁻¹
    return log_pz + log_det

x_flow_test = 2.5
log_p_flow  = flow_log_prob(x_flow_test)
log_p_direct = stats.norm.logpdf(x_flow_test, 2.0, 1.5)
print(f"  Flow log p(x={x_flow_test}): flow={log_p_flow:.4f}  direct={log_p_direct:.4f} ✓")

sub("20.8 Regularization — Probabilistic Interpretation")
regs = {
    "L2 (Ridge)": "MAP with Gaussian prior N(0, 1/2λ·I)",
    "L1 (Lasso)": "MAP with Laplace  prior Lap(0, 1/2λ)",
    "Dropout":    "Approximate Bayesian inference (Bernoulli mask)",
    "Weight decay":"Gaussian prior on weights",
}
for name, meaning in regs.items():
    print(f"  {name:<14}: {meaning}")

sub("20.9 Score Function & Fisher Information")
# Score: s(θ) = ∇_θ log p(x|θ)
# Fisher: I(θ) = E[s(θ)·s(θ)ᵀ] = -E[∇²_θ log p(x|θ)]
# For N(μ,σ²): I(μ) = 1/σ², I(σ²) = 1/(2σ⁴)
sigma_fi = 2.0
fisher_mu   = 1.0 / sigma_fi**2
fisher_sig2 = 1.0 / (2*sigma_fi**4)
# Cramer-Rao: Var(θ̂) ≥ 1/I(θ)
cr_mu   = 1.0 / fisher_mu    # lower bound on Var(μ̂)
cr_sig2 = 1.0 / fisher_sig2
print(f"  Gaussian Fisher I(μ)={fisher_mu:.4f}  I(σ²)={fisher_sig2:.4f}")
print(f"  Cramer-Rao: Var(μ̂) ≥ {cr_mu:.4f}  Var(σ̂²) ≥ {cr_sig2:.4f}")
# Verify: Var(X̄) = σ²/n  (MLE for μ achieves Cramer-Rao!)
n_cr = 100
print(f"  Var(X̄) with n={n_cr}: σ²/n = {sigma_fi**2/n_cr:.4f}  (matches CR bound ✓)")

sub("20.10 Monte Carlo Methods")
# MC estimation: E_p[f(X)] ≈ (1/N)Σf(xᵢ)
# Estimate E[sin(X)] for X~Uniform(0,π)
N_mc = 50_000
X_mc_est = np.random.uniform(0, math.pi, N_mc)
mc_estimate = np.mean(np.sin(X_mc_est))           # should be 2/π≈0.6366
exact = 2 / math.pi
print(f"  MC estimate E[sin(X)] = {mc_estimate:.5f}  exact = {exact:.5f}")
print(f"  Error O(1/√N) ≈ {1/math.sqrt(N_mc):.5f}")

# Importance Sampling: E_p[f] = E_q[f·(p/q)]
# Estimate E_N(0,1)[exp(-x²)] using q=N(0,2) (wider proposal)
N_is = 20_000
p_dist  = stats.norm(0, 1)     # target
q_dist  = stats.norm(0, 2)     # proposal
x_q     = q_dist.rvs(N_is)
w_is    = p_dist.pdf(x_q) / q_dist.pdf(x_q)   # importance weights
f_is    = np.exp(-x_q**2)
is_est  = np.mean(w_is * f_is)
mc_est  = np.mean(np.exp(-np.random.normal(0,1,N_is)**2))  # direct MC
exact_is = math.sqrt(math.pi/2) * stats.norm.cdf(math.sqrt(2)) * 2 - math.sqrt(math.pi/2)
print(f"\n  Importance sampling E[e^{{-X²}}]: IS={is_est:.5f}  direct MC={mc_est:.5f}")

# MC Dropout — Bayesian neural network uncertainty
class MCDropoutNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(1, 32), nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(32, 16), nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(16, 1))
    def forward(self, x): return self.net(x)

mc_net = MCDropoutNet()
mc_net.train()   # keep dropout active at test time
x_test_mc = torch.tensor([[2.5]])
T_mc = 100
preds_mc = torch.cat([mc_net(x_test_mc) for _ in range(T_mc)])
mean_pred = preds_mc.mean().item()
var_pred  = preds_mc.var().item()
print(f"\n  MC Dropout (T={T_mc}): mean={mean_pred:.4f}  variance={var_pred:.4f}")


# ──────────────────────────────────────────────────────────────────────────────
# MASTER FORMULA REFERENCE — Quick Verification
# ──────────────────────────────────────────────────────────────────────────────
header("MASTER FORMULA REFERENCE — Verification")

data_ref = np.array([0.4, 0.3, 0.2, 0.1])
q_ref    = np.array([0.25]*4)

checks = {
    "H(p)=-Σp·log(p)"         : entropy(data_ref),
    "D_KL(p||q)=Σp·log(p/q)"  : kl_divergence(data_ref, q_ref),
    "H(p,q)=H(p)+KL"          : entropy(data_ref)+kl_divergence(data_ref,q_ref),
    "H(p,q) direct"            : cross_entropy(data_ref, q_ref),
    "I(X;Y)=H(X)-H(X|Y)"      : MI_xy,
    "E[X] die"                 : E_die,
    "Var=E[X²]-(E[X])²"       : var_formula,
}
for name, val in checks.items():
    print(f"  {name:<35} = {val:.5f}")

# Tower property
print(f"\n  E[X] direct={e_direct:.4f}  E[E[X|Y]]={e_tower:.4f}  ← Tower ✓")

# Bayes' theorem
lik_r, pr_r, ev_r = 0.99, 0.01, p_pos
post_r = lik_r * pr_r / ev_r
print(f"  Bayes P(D|+)={post_r:.4f}  ← base rate problem ✓")

# ELBO bound
print(f"  ELBO = E_q[log p(x|z)] - KL(q||p) ≤ log p(x)")
print(f"  VAE KL (3D latent) = {KL_enc.item():.4f}")


print(f"\n{DIVIDER}")
print("  ✅ All 20 sections implemented and verified.")
print("  Libraries: numpy · math · torch · sklearn · tensorflow · scipy")
print(DIVIDER)
